---
title: "Hypothesis Tests"
output: html_notebook
---

```{r}
# install package if needed 
# install.packages('ggplot2')
# install.packages('tidyverse')
```

```{r}
# Load R packages
library(ggplot2)
library(tidyverse)

```

```{r}
# Load built-in dataset into the environment
# midwest: a dataset in ggplot2 with demographic information of midwest counties
data(midwest)

midwest

```

```{r}
# Look at the data
head(midwest)

```

```{r}
# Look at the first 10 values in the percollege variable
head(midwest$percollege, 10)

# Get summary statistics of the percollege variable 
summary(midwest$percollege)

# Set plot size
options(repr.plot.width=6, repr.plot.height=3)

# Histogram of percollege
ggplot(midwest, aes(percollege)) + geom_histogram()

# Bar chart of percollege
ggplot(midwest, aes(percollege)) + geom_boxplot() + coord_flip()

```


```{r}
# One sample t-test for difference in means

t.test(midwest$percollege, mu = 25, paired = FALSE, alternative = 'two.sided', conf.level = 0.95)

```


```{r}
t.test(midwest$percollege, mu = 25, paired = FALSE, alternative = 'two.sided', conf.level = 0.90)

```

```{r}
t.test(midwest$percollege, mu = 25, paired = FALSE, alternative = 'two.sided', conf.level = 0.99)

```


```{r}
t.test(midwest$percollege, mu = 25, paired = FALSE, alternative = 'less', conf.level = 0.95)


```


```{r}
t.test(midwest$percollege, mu = 25, paired = FALSE, alternative = 'greater', conf.level = 0.95)


```

