---
title: "Module-2-R-Practice-Template.Rmd"
output: html_document
---

```{r}
# Install the libraries if needed

# install package if needed 
# install.packages("fitdistrplus")
# install.packages("actuar")
# install.packages('ggplot2')
# install.packages('tidyverse')

# Load R packages
library(fitdistrplus)
library(actuar)
library(stats)
library(ggplot2)
library(tidyverse)

```



```{r}
# 1. Use the Walmart data. These are the survey responses of a sample of Walmart customers. Create a sample distribution of the time since last purchase for a customer i.e. Create a histogram of the variable Time_Since_Last_Purchase.

# Which distribution does the variable Time_Since_Last_Purchase mostly likely follow?

walmart_data <- read.csv("walmart_data.csv")
walmart_data
head(walmart_data)

pur.time =density(walmart_data$Time_Since_Last_Purchase)
plot(pur.time,col=2, main="Plot Density for purchase time", sub=paste("R",format(Sys.time(), "%Y-%b-%d %H:%S")))

hist(walmart_data$Time_Since_Last_Purchase, xlab= "Last purchase time", ylab= "Frequency", main= "Histogram of Time since Last Purchase", prob=T, col= 5, sub=paste("R Pratice Quiz",format(Sys.time(),"%Y-%b-%d %H:%S")))
lines(pur.time, col= "red")

hist(walmart_data$Time_Since_Last_Purchase, col= 5, xlab= "Last purchase time", ylab= "Frequency", main= "Histogram of Time since Last Purchase", sub=paste("R Pratice Quiz",format(Sys.time(),"%Y-%b-%d %H:%S")))



```

```{r}
# 2. Use the Walmart data. These are the survey responses of a sample of Walmart customers. Create a sampling distribution using 1000 samples drawn for the time since last purchase for a customer. i.e. Draw 1000 samples from the variable Time_Since_Last_Purchase and calculate the sample mean for each sample. Create a histogram of the sample means. 

# Which distribution does the sampling distribution of Time_Since_Last_Purchase most likely follow?

# samples to draw
n = 1000 

# create an empty vector to store sample means
sample_means = numeric(n)

# draw samples and calculate means
for (i in 1:n) {
  sample = sample(walmart_data$Time_Since_Last_Purchase, size = n, replace = TRUE)
  sample_means[i] = mean(sample)
}

# Create a histogram of the sample means for 'Time_Since_Last_Purchase'
hist(sample_means, main = "Histogram of Sampling Distribution of Time Since Last Purchase", xlab = "Mean Time Since Last Purchase")

```

```{r}
# 3. Use the Walmart data. These are the survey responses of a sample of Walmart customers. Create a sample distribution of the amount of spending by a customer last year. i.e. Create a histogram of the variable Spending_Last_Year. 

# Which distribution does the variable Spending_Last_Year mostly likely follow?

hist(walmart_data$Spending_Last_Year, col= 5, xlab= "Spending Last Year", ylab= "Frequency", main= "Histogram of Spending Last Year", sub=paste("R Pratice Quiz",format(Sys.time(),"%Y-%b-%d %H:%S")))


```

```{r}
# 4. Use the Walmart data. These are the survey responses of a sample of Walmart customers. Create a sampling distribution using 1000 samples drawn for the spending by a customer last year. i.e. Draw 1000 samples from the variable Spending_Last_Year and calculate the sample mean for each sample. Create a histogram of the sample means. 

# Which distribution does the sampling distribution of Spending_Last_Year most likely follow?

# samples to draw
n = 1000 

# create an empty vector to store sample means
sample_means = numeric(n)

# draw samples and calculate means
for (i in 1:n) {
  sample = sample(walmart_data$Spending_Last_Year, size = n, replace = TRUE)
  sample_means[i] = mean(sample)
}

# Create a histogram of the sample means for 'Spending last year'
hist(sample_means, main = "Histogram of Sampling Distribution of Spending Last Year", xlab = "Mean Time Spending Lasr Year Purchase")


```

```{r}
# 5. Use the Walmart data. Use the t.test() function to find the 95% confidence interval for the mean time since last purchase for a customer last year. Use paired = False, alternative = 'two.sided' in the t.test() function.

# What is the lower bound of the confidence interval? 

# What is the upper bound of the confidence interval? 

# Round the answers to nearest 2 decimals. 

t.test(walmart_data$Time_Since_Last_Purchase, paired = FALSE, alternative = 'two.sided', conf.level = 0.95)

```


```{r}
# 6. Use the Walmart data. Use the t.test() function to find the 95% confidence interval for the mean spending by a customer last year. Use paired = False, alternative = 'two.sided' in the t.test() function.

# What is the lower bound of the confidence interval? 

# What is the upper bound of the confidence interval? 

# Round the answers to nearest 2 decimals. 

t.test(walmart_data$Spending_Last_Year, paired = FALSE, alternative = 'two.sided', conf.level = 0.95)

```



```{r}
# 7. Use the Walmart data. Use the prop.test() function to find the 95% confidence interval for the proportion of customers who made a purchase last month (Shopped_Last_Month). 

# What is the lower bound of the confidence interval? 

# What is the upper bound of the confidence interval? 

# Round the answers to nearest 2 decimals. 



count_0 = sum(walmart_data$Shopped_Last_Month == 0)
count_1 = sum(walmart_data$Shopped_Last_Month == 1)

# perform z-test for proportions
prop.test(c(count_0, count_1), c(length(walmart_data$Shopped_Last_Month), length(walmart_data$Shopped_Last_Month)),  alternative = 'two.sided', conf.level = 0.95)
```

```{r}
# 8. Use the Walmart data. Use the prop.test() function to find the 99% confidence interval for the proportion of customers who made a purchase last month (Shopped_Last_Month). 

# What is the lower bound of the confidence interval? 

# What is the upper bound of the confidence interval? 

# Round the answers to nearest 2 decimals. 



count_0 = sum(walmart_data$Shopped_Last_Month == 0)
count_1 = sum(walmart_data$Shopped_Last_Month == 1)

# perform z-test for proportions
prop.test(c(count_0, count_1), c(length(walmart_data$Shopped_Last_Month), length(walmart_data$Shopped_Last_Month)),  alternative = 'two.sided', conf.level = 0.99)
```

```{r}
# 9. Use the Walmart data. Use the prop.test() function to find the 90% confidence interval for the proportion of customers who made a purchase last month (Shopped_Last_Month). 

# What is the lower bound of the confidence interval? 

# What is the upper bound of the confidence interval? 

# Round the answers to nearest 2 decimals. 


count_0 = sum(walmart_data$Shopped_Last_Month == 0)
count_1 = sum(walmart_data$Shopped_Last_Month == 1)

# perform z-test for proportions
prop.test(c(count_0, count_1), c(length(walmart_data$Shopped_Last_Month), length(walmart_data$Shopped_Last_Month)),  alternative = 'two.sided', conf.level = 0.90)
```

```{r}
# 10. In the question above, which confidence level generates the widest confidence interval? 


```

99%


```{r}
# 11. # In a report of up to 4 pages. Include the following: 

# - Choose 2 more variables from the Walmart data. For each variable: 
# - Create a sample distribution. 
# - Create a sampling distribution using 10,000 samples drawn. 
# - Compare the sample distribution with the sampling distribution. Describe the shape of both distributions. What is the theorem that predicts the sampling distribution will approach the normal distribution when a large number of samples are drawn?

# In up to 300 words, describe a situation or problem from your job, everyday life, current events, etc., for which a confidence interval would be useful for decision making. Describe the business problem and stakeholders. i.e. Who (person, group, organization) would be interested in solving this business problem? Describe up to 5 variables that can be used.

hist(walmart_data$Prices_Important, col= 5, xlab= "Prices Important", ylab= "Frequency", main= "Histogram of Prices Important", sub=paste("R Pratice Quiz",format(Sys.time(),"%Y-%b-%d %H:%S")))


hist(walmart_data$Credit_Card_Cost_High, col= 4, xlab= "Credit card cost High", ylab= "Frequency", main= "Histogram of High credit card cost", sub=paste("R Pratice Quiz",format(Sys.time(),"%Y-%b-%d %H:%S")))

# samples to draw
n = 10000

# create an empty vector to store sample means
sample_means = numeric(n)

# draw samples and calculate means
for (i in 1:n) {
  sample = sample(walmart_data$Prices_Important, size = n, replace = TRUE)
  sample_means[i] = mean(sample)
}

# Create a histogram of the sample means for 'Prices Important'
hist(sample_means, col= 6, main = "Histogram of Sampling Distribution of Prices Important", xlab = "Mean Time Prices Important")


# samples to draw
n = 10000 

# create an empty vector to store sample means
sample_means = numeric(n)

# draw samples and calculate means
for (i in 1:n) {
  sample = sample(walmart_data$Credit_Card_Cost_High, size = n, replace = TRUE)
  sample_means[i] = mean(sample)
}

# Create a histogram of the sample means for 'Credit card cost high'
hist(sample_means, main = "Histogram of Sampling Distribution of Credit card cost High", col= 7, xlab = "Mean of Credit card cost high")
```

```{r}
# 12. Upload a R Markdown file with all code and visualizations used to answer all questions above. You may use the template Module-2-R-Practice-Template.Rmd. 

```

