

```{r}
# Install the sqldf package
# install.packages("sqldf")
# install.packages("corrplot")
# install.packages("mice")

# Load the mice package
library(mice)
# Analyzing missing data pattern in customer_churn data set
# md.pattern(customer_churn)
# Load the sqldf package
library(sqldf)
# Load the corrplot package
library(corrplot)
# Your SQL query
# sqldf("select sum(MonthlyCharge + OverageFee) As Rev from customer_churn")

```

```{r}
customer_churn <- read.csv("churn_data.csv")
customer_churn
str(customer_churn)
summary(customer_churn)
```
```{r}
#####Correlation plot of all features #####
# Compute correlation on all columns except the last
cor(customer_churn[, -ncol(customer_churn)])
# Select only numeric columns for correlation
# cor(customer_churn[, sapply(customer_churn, is.numeric)])
#cor(customer_churn)
head(customer_churn)
tail(customer_churn)
is.na(customer_churn)
na.omit(customer_churn)
```
```{r}
##### produce one correlation plot #####
#Project_cor <- cor(customer_churn,method="pearson")
# Select only numeric columns for Pearson correlation
numeric_columns <- customer_churn[, sapply(customer_churn, is.numeric)]
Project_cor <- cor(numeric_columns, method = "pearson")

# Now you can create the correlation plot
corrplot(Project_cor, method = "circle", mar = c(1, 1, 0, 1))



```
```{r}
#### produce one density and histogram plots together####
usage_den <- density(customer_churn$DataUsage) 
plot(usage_den,col=4,main="Plot for density",sub=paste("R",format(Sys.time(),"%Y-%b-%d%H:%S")))

```

```{r}
Daycals_den <- density(customer_churn$DayCalls)
plot(usage_den,col=4,main="Plot for density",sub=paste("R",format(Sys.time(),"%Y-%b-%d%H:%S")))
Daycals_den
```

```{r}
hist(customer_churn$DataUsage,main="Data Usage",prob=TRUE,
xlab="Usage in GB",ylab="Density",
sub=paste("R",format(Sys.time(),"%Y-%b-%d%H:%S")),col=4)

lines(usage_den,col=5)

```

```{r}
#### produce pie plot/bar plot and a histogram based on the features of your choice in your dataset ###
T=table(customer_churn$DataPlan)
T
barplot(T,main="Bar Plot of Telecom customer churn",xlab="Active Data Plan",ylab="Frequency",sub=paste("R",format(Sys.time(),"%Y-%b-%d%H:%S")),col=4)

```

```{r}
#### pie chart ###
T=table(customer_churn$DataPlan)
T
colors<-c("red","blue")
pie(T,main="Pie Chart of Telecom customer churn",xlab="Active Data Plan",ylab="Frequency",sub=paste("R",format(Sys.time(),"%Y-%b-%d%H:%S")),col=colors)

```

```{r}
#### Histogram Chart ####

hist(customer_churn$DataUsage,main="Histogram of Data Usage",xlab="Data Usage in GB",ylab="Frequency",sub=paste("R",format(Sys.time(),"%Y-%b-%d%H:%S")),col=4)
```



```{r}
#### Count no of customers that use >= 1GB ####
High_Data_Users <- sqldf("select count(DataUsage) from customer_churn where DataUsage >=1" )
High_Data_Users
Low_Data_Users <- sqldf("select count(DataUsage) from customer_churn where DataUsage <1" )
Low_Data_Users
Rev <- sqldf("select sum(MonthlyCharge + OverageFee) As Rev,DataUsagecat from customer_churn group by DataUsagecat" )
Rev1 <- sqldf("select sum(MonthlyCharge + OverageFee) As Rev from customer_churn" )
Rev1
```


```{r}
#### Create Sub-categories of Data Users ####
customer_churn$DataUsagecat[customer_churn$DataUsage <1] <- "Low_Users"
customer_churn$DataUsagecat[customer_churn$DataUsage >=1 & customer_churn$DataUsage <=2.7] <-"Avg_Users"
customer_churn$DataUsagecat[customer_churn$DataUsage >2.7] <-"High_Users"
```

```{r}

is.na(customer_churn)
#### Create a Distribution for DataUsers ####
A=table(customer_churn$DataUsagecat)
A
Usage_plot <- barplot(A,main="Categorization of Data Users",sub=paste("R",format(Sys.time(),"%Y-%b-%d%H:%S")),col=4)
data_plot <- barplot(place,main="Categorization of Data Users",sub=paste("R",format(Sys.time(),"%Y-%b-%d%H:%S")),col=4)
B=table(Rev)
B
place<-c(34325,44635,142206)

plot(customer_churn$DataUsage,customer_churn$DataPlan,lty=2,pch=10,xlab="Width",ylab="Lenght",col="red")

```


```{r}
#### Check the number of colmns and rows ########
names(customer_churn)
str(customer_churn)
dim(customer_churn)
```

```{r}
#### Use Mice Package to report the pattern including the related plot ###
# md.pattern(customer_churn)

# Get the missing data pattern information
mdpat <- md.pattern(customer_churn, plot = FALSE)

# Extract the number of missing values for each variable
# It is typically in the last row of the mdpat object
missing_values <- mdpat[nrow(mdpat), ]

# Extract the variable names from the mdpat object
var_names <- colnames(mdpat)

# Create a bar plot with space for vertical labels
barplot_heights <- barplot(missing_values, 
        names.arg = rep("", length(missing_values)), 
        main = "Missing Data Pattern",
        xlab = "Variables", 
        ylab = "Number of Missing Values",
        las = 1)

# Concatenate variable names with the number of missing values
labels_with_counts <- paste(var_names, ":", missing_values)

# Add the variable names and number of missing values as vertical axis labels
# Adjust the text's y-position to be below the x-axis
text(x = barplot_heights, 
     y = -0.5 * max(missing_values), 
     labels = labels_with_counts, 
     srt = 90, 
     adj = 1, 
     xpd = TRUE, 
     cex = 0.5)

# Reset the margins to default if necessary
par(mar = c(5, 4, 4, 2) + 0.1)

```


```{r}
##### Check the existence of NA and exclude them ######
is.na(customer_churn)

```


