---
title: "Strings in R (stringr)"
output: html_notebook
---

```{r}
# install package if needed 
# install.packages('ggplot2')
# install.packages('tidyverse')
# install.packages('dplyr')
# install.packages('stringr')
```

```{r}
# Import libraries
library(ggplot2)
library(tidyverse)
library(dplyr)
library(stringr)

```


```{r}
# Common Functions

str_length('this is a string.')

str_c('x', 'y')
str_c('x', 'y', 'z')

x <- 'abc'
str_c('|-', x, '-|')

y <- 123
y
as.character(y)

```


```{r}
# add if conditions
name <- 'Sam'
time_of_day <- 'morning'
birthday <- FALSE

str_c(
  'Good ', time_of_day, ' ', name,
  if (birthday) ' and HAPPY BIRTHDAY',
  '.'
)

name <- 'Dave'
time_of_day <- 'morning'
birthday <- TRUE

str_c(
  'Good ', time_of_day, ' ', name,
  if (birthday) ' and HAPPY BIRTHDAY',
  '.'
)

str_c(c('x','y','z'), collapse = ', ')

x <- c('Apple', 'Banana', 'Pear')
x
str_sub(x, 1, 3) 

str_sub(x, -3, -1) 

str_sub(x, 1, 1) <- str_to_lower(str_sub(x, 1, 1))
x

str_to_upper('i')
str_to_upper('apple')

x <- c('apple', 'eggplant', 'banana')

str_sort(x, locale = 'en')

```


```{r}
# Applications - Detect matches

x <- c('apple', 'banana', 'pear')
str_detect(x, 'e')

head(words, 100)
length(words)

str_detect(words, '^t')
sum(str_detect(words, '^t'))

str_detect(words, '[aeiou]$')
mean(str_detect(words, '[aeiou]$'))

str_subset(words, 'x$')

x <- c('apple', 'banana', 'pear')
str_count(x, 'a')

str_count('abababa', 'aba')

```


```{r}
# Applications - Extract matches

head(sentences, 20)
length(sentences)

colours <- c(' red ', ' orange ', ' yellow ', ' green ', ' blue ', ' purple ', ' black ')
colour_match <- str_c(colours, collapse = '|')
colour_match

has_colour <- str_subset(sentences, colour_match)
has_colour

matches <- str_extract(has_colour, colour_match)
matches

length(matches)

more <- sentences[str_count(sentences, colour_match) > 1]
str_view_all(more, colour_match)

str_extract(more, colour_match)

str_extract_all(more, colour_match)

```


```{r}
# Applications - Grouped matches


noun <- "(a|the) ([^ ]+)"

has_noun <- str_subset(sentences, noun) 
has_noun <- head(has_noun, 10)
has_noun

str_extract(has_noun, noun)

```


```{r}
# Applications - Replacing matches


x <- c('apple', 'pear', 'banana')
str_replace(x, '[aeiou]', '-') 

str_replace_all(x, '[aeiou]', '-') 

x <- c('1 house', '2 cars', '3 people')
str_replace_all(x, c('1' = 'one', '2' = 'two', '3' = 'three')) 

```


```{r}
# Applications - Splitting

sentences %>% head(5)

sentences %>% head(5) %>% str_split(' ')

sentences %>% head(5) %>% str_split(' ') %>% sapply(head, 1)

sentences %>% head(5) %>% str_split(' ') %>% sapply(tail, 1)

'a|b|c|d' %>% str_split('\\|')

```

