---
title: "Hypothesis Testing II"
output: html_notebook
---

```{r}
# install package if needed 
# install.packages('ggplot2')
# install.packages('tidyverse')
```

```{r}
# Load R packages
library(ggplot2)
library(tidyverse)

```

```{r}
# Load built-in dataset into the environment
# midwest: a dataset in ggplot2 with demographic information of midwest counties
data(midwest)

midwest

```

```{r}
# Look at the data
head(midwest)

```

```{r}
head(midwest$percollege, 10)

summary(midwest$percollege)

options(repr.plot.width=6, repr.plot.height=3)

ggplot(midwest, aes(percollege)) + geom_histogram()

```

```{r}
cor(midwest$poptotal, midwest$popdensity)

```

```{r}
# One sample t-test for difference in means

# Use t.test function
# Parameters:
# mu: value to be tested against
# paired: paired test or not
# alternative: two.sided, less, or greater
# conf.level: confidence level

t.test(midwest$percollege, mu = 25, paired = FALSE, alternative = 'two.sided', conf.level = 0.95)

t.test(midwest$percollege, mu = 25, paired = FALSE, alternative = 'less', conf.level = 0.95)


```

```{r}
# Two sample t-test for difference in means
# Use t.test function
# e.g. Test equality of variable y by variable x (group): t.test(y ~ x, data = df)

df <- midwest %>% filter(state == 'WI' | state == 'IL')

ggplot(df, aes(state, percollege)) + geom_boxplot()

t.test(percollege ~ state, data = df, conf.level = 0.95)


```

```{r}
# z-test for difference in proportions
# Use prop.test function
# prop.test(x, n, alternative = c('two.sided, 'less, 'greater'), conf.level = 0.95)
# Parameters:
# x: a vector of counts of successes
# n: a vector of counts of trials
# alternative: two.sided, less, or greater
# conf.level: confidence level

# Suppose 40 out of 400 (10%) women are promoted, and 196 out of 3270 (6%) men are promoted 
# Test the null hypothesis that the 2 proportions are equal 

prop.test(c(40,196),c(400,3270), alternative = 'two.sided', conf.level = 0.95)


```

```{r}
# Paired t-test for difference in means
# In paired t-test, each subject is tested twice
# Use t.test function
# Parameters:
# mu: value to be tested against
# paired: set to TRUE
# alternative: two.sided, less, or greater
# conf.level: confidence level

sleep


t.test(extra ~ group, data = sleep, paired = TRUE, alternative = 'two.sided', conf.level = 0.95)

```

```{r}
# Chi-squared test 
# Test if there is a statistically significant difference between treatment and cocaine addiction.

df = data.frame(success = c(14,6,4),
                failure = c(10,18,20))

rownames(df) = c('Desipramine', 'Lithium', 'Placeco')

dt = as.table(as.matrix(df))
dt

chisq = chisq.test(dt)
chisq


chisq$expected 
chisq$observed 
chisq$p.value 

```


