---
title: "LastName-FirstName-Project3.Rmd"
output: html_document
---


```{r}
cat("\014") # clears console 
rm(list = ls()) # clears global environment 
try(dev.off(dev.list()["RStudioGD"]), silent = TRUE) # clears plots 
try(p_unload(p_loaded(), character.only = TRUE), silent = TRUE) # clears packages 
options(scipen = 100) # disables scientific notation for entire R session

# You should do this line only once in the entire course. 
# install.packages("pacman") 

library(pacman)
p_load(testthat) 
p_load(tidyverse)
p_load(lubridate)
p_load(ggplot2)

```

# Assignment Part 0: Downloading and Importing the Dataset

```{r}
# 1. Download the file books.csv from Canvas and read the dataset into R.


```

# Assignment Part 1: Cleaning the Dataset

```{r}
# 1. The janitor package contains helpful functions that perform basic maintenance of your data frame. Use the clean_names function to standardize the names in your data frame.

```

```{r}
# 2. The lubridate package contains helpful functions to convert dates represented as strings to dates represented as dates. Convert the first_publish_date column to a type date using the mdy function.


```

```{r}
# 3. Using the year function in lubridate, extract the year from the first_publish_date column place it in a new column named year.


```

```{r}
# 4. Reduce your dataset to only include books published between 1990 and 2020 (inclusive).


```

```{r}
# 5. Remove the following columns from the data set: publish_date, edition, characters, price, genres, setting, and isbn.


```

```{r}
# 6. Keep only books that are fewer than 1200 pages.


```

# Assignment Part 2: Data Analysis (Use the result from Q6 above for the following questions.)

```{r}
# 1. Use the glimpse function to produce a long view of the dataset.


```

```{r}
# 2. Use the summary function to produce a breakdown of the statistics of the dataset.


```


```{r}
# 3. Create a rating histogram with the following criteria.
# – The y-axis is labeled “Number of Books.”
# – The x-axis is labeled “Rating.”
# – The title of the graph “Histogram of Book Ratings.”
# – The graph is filled with the color “red.”
# – Set a binwidth of .25.
# – Use theme_bw().



```


```{r}
# 4. Create a boxplot of the number pages per book in the dataset with the following requirements.
# – The boxplot is horizontal.
# – The x-axis is labeled “Pages.”
# – The title is “Box Plot of Page Counts.”
# – Fill the boxplot with the color magenta.
# – Use the theme theme_economist from the ggthemes package.

# install.packages('ggthemes')



```

```{r}
# 5. Group the data by publisher and produce a summary data frame containing each publisher and their associated number of books in the dataset. With that data frame, make the following refinements:
# – Remove any rows that contain NAs.
# – Remove any publishers with fewer than 250 books.
# – Order the data frame by the total number of books in descending order.
# – Make the publisher into a factor with the levels defined by the current ordering of the publisher.
# – Add a column to the data frame with cumulative count of books.
# – Add a column to the data frame with the relative frequency of books.
# – Add a column to the data frame with the cumulative relative frequency of books. 


```

```{r}
# 6. Using the data frame constructed in the prior problem, create a Pareto Chart with an ogive of cumulative counts formatted with the following additional criteria:

# – The bars are filled with the color cyan.
# – The x-axis label is “Publisher.”
# – The y-axis label is “Number of Books.”
# – The title is “Pareto and Ogive of Publisher Book Counts (1990 - 2020).”
# – Use the theme theme_clean().
# – Rotate the x-axis labels by 45 degrees.


```

```{r}
# 7. Create a scatter plot of pages vs. rating for the books data frame with the following requirements:
# – Color the points based on the year of publication.
# – The x-axis is labeled “Pages.”
# – The y-axis is labeled “Rating.”
# – The graph is titled “Scatter Plot of Pages vs. Rating.”
# – Use the theme theme_tufte().



```

```{r}
# 8. Create a data frame from the books data frame that contains a count of the number of books by year and the average rating for each year.


```

```{r}
# 9. Create a line plot with from this data frame with points representing the counts per year from 1990 - 2020. Color the points for each year with the average rating. The size of each data point should vary with the average rating. Format with the following specifications:
# – The graph is titled “Total Number of Books Rated Per Year.”
# – The theme is theme_excel_new().



```

```{r}
# 10. R has built-in functions to computer the sample mean (mean), sample variance (var), and sample standard deviation (sd). The function 'calc_mean' below takes in a vector of values and returns the average. Using the function as a template, create two more functions; one to compute the population variance (pop_var) and the other one to compute the population standard deviation (sd_var). See module 4's slides for the difference between sample and population variance and standard deviation. You may not use the three built-in functions listed above, but may use other built-in functions. All three functions should accept a single vector of values and return the corresponding computed result.

```

```{r}
# 11. Consider the complete dataset of books to be the population you are analyzing. Compute population stats for the average, variance, and standard deviation of the book rating.


```

```{r}
# 12. Create three samples of size 100 from the books data frame using the function sample(df$rating, size = 100, replace = FALSE). For each sample, compute sample statistics for mean, variance and standard deviation of the book rating. Compare these results with the population stats in your report.


```

```{r}
# 13. Create one or more additional visualizations based on the existing data or additional analysis that you perform.

```

```{r}
# 14. Write an executive summary report that contains an overview of your analysis, the visualizations you created with textual descriptions of key takeaways, and any key statistics that were computed in your analysis.



```


```{r}
# Run this cell to check your answers 
library(pacman)
p_load(testthat) 
p_load(tidyverse)
p_load(lubridate)
p_load(ggplot2)
test_file("project3_tests.R")

```



